version: '2'
services:

  # Flask application.
  app:
    image: jsanweb/bank-status
    build: .
    container_name: app
    restart: always
    env_file: ./deploy/env/dev/app.env
    command: python run.py
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
      - ./logs:/usr/src/logs
    # stdin_open: true
    # tty: true
